export const consonants = [
  {
    id: 1,
    letter: "ㄱ",
    sound: "ㄱ",
    example: "가방, 가위, 강아지, 개미, 고양이, 구름, 기차",
  },
  {
    id: 2,
    letter: "ㄴ",
    sound: "ㄴ",
    example: "나무늘보, 나비, 나침반, 냉장고, 노래, 놀이터, 눈사람",
  },
  {
    id: 3,
    letter: "ㄷ",
    sound: "ㄷ",
    example: "다리, 달력, 달팽이, 당근, 도넛, 도서관, 돼지",
  },
  {
    id: 4,
    letter: "ㄹ",
    sound: "ㄹ",
    example: "라디오, 라면, 램프, 로봇, 리모컨, 리본, 리코더",
  },
  {
    id: 5,
    letter: "ㅁ",
    sound: "ㅁ",
    example: "마스크, 모자, 목걸이, 무당벌레, 무지개, 문어, 미끄럼틀",
  },
  {
    id: 6,
    letter: "ㅂ",
    sound: "ㅂ",
    example: "바나나, 바다, 바이올린, 버스, 배추, 부모, 비행기",
  },
  {
    id: 7,
    letter: "ㅅ",
    sound: "ㅅ",
    example: "사과, 사자, 새우, 선인장, 수박, 시계, 신호등",
  },
  {
    id: 8,
    letter: "ㅇ",
    sound: "ㅇ",
    example: "아기, 아빠, 언니, 엄마, 연필, 오리, 우주선",
  },
  {
    id: 9,
    letter: "ㅈ",
    sound: "ㅈ",
    example: "자동차, 자전거, 장미, 전기, 젓가락, 조개, 지갑",
  },
  {
    id: 10,
    letter: "ㅊ",
    sound: "ㅊ",
    example: "창문, 책상, 초콜릿, 치마, 친구, 침대, 칫솔",
  },
  {
    id: 11,
    letter: "ㅋ",
    sound: "ㅋ",
    example: "카메라, 카멜레온, 컴퓨터, 코끼리, 콜라, 키위, 킥보드",
  },
  {
    id: 12,
    letter: "ㅌ",
    sound: "ㅌ",
    example: "타조, 탁자, 탬버린, 터널, 토끼, 토마토, 티셔츠",
  },
  {
    id: 13,
    letter: "ㅍ",
    sound: "ㅍ",
    example: "파리, 편지, 포도, 풍선, 프린터, 피아노, 피자",
  },
  {
    id: 14,
    letter: "ㅎ",
    sound: "ㅎ",
    example: "하마, 하모니카, 해바라기, 햄버거, 헬리콥터, 호랑이, 호두",
  },
];
export const vowels = [
  {
    id: 1,
    letter: "ㅏ",
    sound: "ㅏ",
    example: "아시아, 아이스크림, 아침, 아파트, 악어, 안경",
  },
  {
    id: 2,
    letter: "ㅑ",
    sound: "ㅑ",
    example: "야경, 야구, 야자수, 야채, 약속, 얌체",
  },
  {
    id: 3,
    letter: "ㅓ",
    sound: "ㅓ",
    example: "어깨, 어른, 어린이, 어항, 언덕, 얼룩말",
  },
  {
    id: 4,
    letter: "ㅕ",
    sound: "ㅕ",
    example: "여름, 여우, 여자, 여행, 연필, 열쇠",
  },
  {
    id: 5,
    letter: "ㅗ",
    sound: "ㅗ",
    example: "오렌지, 오전, 오징어, 오토바이, 오후, 옥수수",
  },
  {
    id: 6,
    letter: "ㅛ",
    sound: "ㅛ",
    example: "요가, 요리, 요술, 요일, 요정, 요트",
  },
  {
    id: 7,
    letter: "ㅜ",
    sound: "ㅜ",
    example: "우산, 우유, 우주, 우체국, 우화, 운동",
  },
  {
    id: 8,
    letter: "ㅠ",
    sound: "ㅠ",
    example: "유니콘, 유령, 유리, 유모차, 유치원, 유학",
  },
  {
    id: 9,
    letter: "ㅡ",
    sound: "ㅡ",
    example: "으르렁, 으뜸, 윽박, 은행, 음식, 음악",
  },
  {
    id: 10,
    letter: "ㅣ",
    sound: "ㅣ",
    example: "이모, 이발소, 이불, 이어폰, 인사, 일기",
  },
];
export const doubleCons = [
  {
    id: 1,
    letter: "ㄲ",
    sound: "쌍기역",
    example: "까닭, 까마귀, 까치, 꼬리, 꾸러미",
  },
  {
    id: 2,
    letter: "ㄸ",
    sound: "ㄸ",
    example: "따오기, 딱따구리, 딸기, 뚜껑, 뜰채",
  },
  {
    id: 3,
    letter: "ㅃ",
    sound: "ㅃ",
    example: "빨강, 빨래, 뺄셈, 뻐꾸기, 뿌리",
  },
  {
    id: 4,
    letter: "ㅆ",
    sound: "ㅆ",
    example: "싸움, 쌍둥이, 쏘가리, 쓰레기통, 씨앗",
  },
  {
    id: 5,
    letter: "ㅉ",
    sound: "ㅉ",
    example: "짜장면, 짜증, 짝궁, 쪽지, 쭈꾸미",
  },
];
export const doubleVow = [
  {
    id: 1,
    letter: "ㅐ",
    sound: "애",
    example: "애교, 애벌레, 애원, 애인, 애정, 애호박",
  },
  {
    id: 2,
    letter: "ㅒ",
    sound: "얘",
    example: "얘기, 얘박, 얘장깐, 얘청",
  },
  {
    id: 3,
    letter: "ㅔ",
    sound: "에",
    example: "에너지, 에러, 에어컨, 에스키모, 엘리베이터",
  },
  {
    id: 4,
    letter: "ㅖ",
    sound: "예",
    example: "예금, 예방, 예술, 예의, 예절, 예측",
  },
  {
    id: 5,
    letter: "ㅘ",
    sound: "와",
    example: "와이어, 와이파이, 와인, 와플, 완두콩, 완성",
  },
  {
    id: 6,
    letter: "ㅙ",
    sound: "왜",
    example: "왜가리, 왜곡, 왜냐하면, 왜소, 왠지",
  },
  {
    id: 7,
    letter: "ㅚ",
    sound: "외",
    example: "외계인, 외교, 외국, 외로움, 외면, 외출",
  },
  {
    id: 8,
    letter: "ㅝ",
    sound: "워",
    example: "워드, 워킹, 워크숍, 워터파크, 원숭이, 월척",
  },
  {
    id: 9,
    letter: "ㅞ",
    sound: "웨",
    example: "웨딩, 웨스트, 웨이브, 웨이터, 웨이팅",
  },
  {
    id: 10,
    letter: "ㅟ",
    sound: "위",
    example: "위로, 위반, 위생, 위성, 위치, 위험",
  },
  {
    id: 11,
    letter: "ㅢ",
    sound: "의",
    example: "의견, 의문, 의미, 의상, 의식, 의자",
  },
];
